/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trongame;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ludfra-7-local
 */
public class connectWindow extends javax.swing.JFrame {

    /**
     * Creates new form connectWindow
     */
    
    Socket server = null;
    
    DataOutputStream out;
    DataInputStream in;
    searchResponseThread searchThread;

    int id = -1;
    int playerCount;
    
    String names[];
    
    serverObject[] serverList = null;
    int serverCount = 0;
    
    public connectWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tronText = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoField = new javax.swing.JTextArea();
        nameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        serverSelectorBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tronText.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        tronText.setText("Tron");

        joinButton.setText("Connect");
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });

        infoField.setColumns(20);
        infoField.setRows(5);
        infoField.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(infoField);

        nameField.setText("Ludde");

        jLabel4.setText("Name:");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        serverSelectorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(tronText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(serverSelectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(joinButton)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tronText, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton)
                    .addComponent(serverSelectorBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed
        //Attempt connection
        try {
            if(server==null){
                join();
            }else if(id==0){
                startRequest();
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(connectWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            infoField.setText("Error: Could not connect to server");
            Logger.getLogger(connectWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_joinButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        search();
    }//GEN-LAST:event_refreshButtonActionPerformed
    public static void main(String[] args) {
        connectWindow w = new connectWindow();
        w.start();
    }
    /**
     * @param args the command line arguments
     */
    public void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connectWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connectWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connectWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connectWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connectWindow().setVisible(true);
            }
        });
    }
    void search(){
        try {
            int port = 1900;
            InetAddress group = InetAddress.getByName("239.255.255.250");
            MulticastSocket broadcastSocket = new MulticastSocket();
            byte[] buffer = "SERVICE REQUEST tronJavaGame".getBytes();
            DatagramPacket packet = new DatagramPacket(buffer, buffer.length, group, port);
            broadcastSocket.send(packet);
            if(searchThread!=null) searchThread.running = false;
            searchThread = new searchResponseThread(this);
            searchThread.start();
            System.out.println("Listener started!");
            
        } catch (UnknownHostException ex) {
            Logger.getLogger(connectWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(connectWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void join() throws UnknownHostException, IOException{
        int index = serverSelectorBox.getSelectedIndex();
        System.out.println("Connecting to: " + serverList[index].ip + ":" + serverList[index].port);
        server = new Socket(serverList[index].ip, serverList[index].port);
        out = new DataOutputStream(server.getOutputStream());
        in = new DataInputStream(server.getInputStream());
        
        out.writeUTF("0|" + nameField.getText());
        out.flush();
        
        Thread waitThread = new joiningThread(this);
        waitThread.start();
    }
    
    void startRequest() throws IOException{
        out.writeUTF("1");
    }
    
    void startGame(){
        gameThread gameInstance;
        gameWindow window = new gameWindow(server);
        gameInstance = new gameThread(server, window.gamePanel, playerCount, id);
        window.gamePanel.game = gameInstance;
        window.setVisible(true);
        window.start();
        gameInstance.update();
        System.out.println("Done!");
        
    }
    
    void setInfo(String info){
        infoField.setText(info);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infoField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton joinButton;
    private javax.swing.JTextField nameField;
    public javax.swing.JButton refreshButton;
    public javax.swing.JComboBox<String> serverSelectorBox;
    public javax.swing.JLabel tronText;
    // End of variables declaration//GEN-END:variables
}

class serverObject{
    String name;
    InetAddress ip;
    int port;
    public serverObject(String name, String ip, String port){
        try {
            if(ip.contains("/")) ip = ip.substring(ip.indexOf("/")+1); //Failsafe
            this.name = name;
            this.ip = InetAddress.getByName(ip);
            this.port = Integer.parseInt(port);
        } catch (UnknownHostException ex) {
            Logger.getLogger(serverObject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
