/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trongame;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import static java.awt.event.KeyEvent.*;
import java.awt.event.KeyListener;

/**
 *
 * @author ludfra-7-local
 */
public class gamePanel extends javax.swing.JPanel{
    gameThread game;

    /**
     * Creates new form gamePanel
     */
    String winnerName = "";
    public gamePanel() {
        initComponents();
        this.setVisible(true);
        this.requestFocus();
        
        
        this.addKeyListener(new KeyListener(){
        @Override
        public void keyTyped(KeyEvent e) {
            
        }

        @Override
        public void keyPressed(KeyEvent e) {
            System.out.println("Key input");
            int code = e.getKeyCode();
            switch(code){
                case VK_W:
                    game.move(0,-1);
                    break;
                case VK_A:
                    game.move(-1,0);
                    break;
                case VK_S:
                    game.move(0,1);
                    break;
                case VK_D:
                    game.move(1,0);
                    break;
            }
            
        }

        @Override
        public void keyReleased(KeyEvent e) {
        }
        });
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(750, 750));
        setMinimumSize(new java.awt.Dimension(750, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        
        if(winnerName!=""){
            g.setFont(new Font("Serif", Font.BOLD, 48));
            g.drawString(winnerName + " wins!", 300, 375);
            return;
        }
        //Draws trail
        for(int i = 0; i < 32; i++){
            for (int j = 0; j < 32; j++) {
            g.setColor(trailColor(game.field[i][j]));
            g.fillRect(i*20, j*20, 20, 20);
            }
        }
        
        //Draws player
        for(int i = 0; i < game.playerCount; i++){
            if(game.pos[i][0]!=-10){
                g.setColor(playerColor(i));
                game.field[game.pos[i][0]][game.pos[i][1]] = i;
                g.fillRect(game.pos[i][0]*20, game.pos[i][1]*20, 20, 20);
            }
        }
        
        
        
        //ImageIcon i = new ImageIcon("C:\\Users\\ludfra-7-local\\Downloads\\circle.jpg");
        //i.paintIcon(this, g, 0, 0);
    }
    
    
    private Color trailColor(int p){
        switch(p){
            case 0:
                return Color.ORANGE;
            case 1:
                return Color.CYAN;
            case 2:
                return Color.RED;
            case 3:
                return Color.GREEN;
            default:
                return new Color(187,187,187);
        }
    }
    
    
    
    private Color playerColor(int p){
        switch(p){
            case 0:
                return new Color(249, 158, 74);
            case 1:
                return new Color(0,125,125);
            case 2:
                return new Color(125,0,0);
            case 3:
                return new Color(0,125,0);
            default:
                return new Color(187,187,187);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
